Keep track of the total bytesize of the queue
ged/loggability pull request #3
Opened 2020-03-05 18:47 UTC by mahmoodkhan

This will protect against exhausting server's memory if the http logging service endpoint is down for extended period of time.

2020-03-31 18:00 UTC, ged requested changes
I have been trying to replicate the problem that this is meant to solve, but when I configure HTTP logging and down the service it's logging to, it behaves in what I consider the best way already (without this patch). It attempts to send the batch of logs to the service, fails, and the executor restarts for the next batch. This both doesn't require the overhead of calculating the size of the queue for every message, but also keeps things much simpler and ensures that when the logging service is restored the most-recent logs are the ones that get shipped instead of the oldest.

Can you describe what you see happening that necessitates this?

2020-03-31 18:00 UTC, ged commented on lib/loggability/log_device/http.rb
> +	DEFAULT_MAX_QUEUE_BYTESIZE = ( 2 ** 10 ) * ( 2 ** 10 ) * ( 2 ** 10 )
You could replace this with `2 ** 30`, which is a bit clearer to me.

2020-03-31 20:25 UTC, mahmoodkhan commented
I wasn't aware that the default behavior has built-in protection against exhausting all available memory on the server. That's good to know. I guess the other benefit to having the patch is that it will keep at least 1 GB worth of log messages instead of just the most recent payload of 5MB or so. If it is preferred to keep the most recent, I can modify the patch to drop the older messages as it reaches capacity.

2020-12-24 21:31 UTC, ged commented
Merged in a9e05a7e95fa1d375d282d3903f3826892a9a519. Thanks for the patch!

2020-12-24 21:31 UTC, closed without merging